workflows:
  blueconnect_user_build:
    name: BlueConnect User APK Build
    max_build_duration: 15
    environment:
      java: 17
    scripts:
      - name: Set permissions and build
        script: |
          chmod +x ./gradlew
          ./gradlew assembleDebug
    artifacts:
      - app/build/outputs/**/*.apk
