workflows:
  blueconnect_user_build:
    name: BlueConnect User APK Build
    max_build_duration: 15
    environment:
      vars:
        JAVA_VERSION: "17"
      android:
        image: "latest"
    scripts:
      - name: Set permissions and build
        script: |
          chmod +x ./gradlew
          ./gradlew assembleDebug
    artifacts:
      - app/build/outputs/**/*.apk
    publishing:
      email:
        recipients:
          - sebastian.migdalin@gmail.com